services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=datajud
      - POSTGRES_USER=datajud
      - POSTGRES_PASSWORD=datajud
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - docker_compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: yahoo-predict-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    command: poetry run uvicorn yahoo-predict.app:app --host 0.0.0.0 --port 8000
    networks:
      - docker_compose
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  docker_compose:
    driver: bridge
